plugins:
  activation_key_button_enabled:
    default: true
    client: true
  activation_key_button_url:
    default: "https://www.discourse.org"
    client: true
  activation_key_button_title:
    default: "Button description here.."
    client: true
  activation_key_button_label:
    default: "Click Me"
    client: true
  activation_key_button_allowed_group:
    default: "trust_level_1"
    client: true
